# Generated by Django 4.2 on 2023-04-06 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_paymentmethod"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paymentmethod",
            field=models.ForeignKey(
                default=-1,
                on_delete=django.db.models.deletion.CASCADE,
                to="market.paymentmethod",
            ),
            preserve_default=False,
        ),
    ]
