# Generated by Django 4.2 on 2023-04-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0003_alter_order_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmethod",
            name="description",
            field=models.CharField(max_length=400),
        ),
    ]
