# Generated by Django 4.2 on 2023-06-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_paymentmethod_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
