# Generated by Django 4.2 on 2023-06-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_paymentmethod_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='large_item',
            field=models.BooleanField(default=False),
        ),
    ]
