# Generated by Django 4.2 on 2023-04-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0008_alter_cart_user_alter_order_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompleteOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=20)),
                ("order_id", models.CharField(blank=True, max_length=36)),
                ("items_detail", models.CharField(max_length=9999)),
                ("paymentmethod", models.CharField(max_length=1000)),
                ("address", models.CharField(max_length=100)),
                ("order_date", models.DateTimeField()),
                ("completed", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="order",
            name="cart",
        ),
        migrations.AddField(
            model_name="order",
            name="items_detail",
            field=models.CharField(default=-1, max_length=9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="order_id",
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AlterField(
            model_name="order",
            name="paymentmethod",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.CharField(max_length=20),
        ),
    ]
