# Generated by Django 4.2 on 2023-04-07 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0009_completeorder_remove_order_cart_order_items_detail_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="completeorder",
            old_name="completed",
            new_name="complete_date",
        ),
    ]
