# Generated by Django 4.2 on 2023-04-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0010_rename_completed_completeorder_complete_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="completeorder",
            old_name="paymentmethod",
            new_name="payment_method",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="paymentmethod",
            new_name="payment_method",
        ),
        migrations.AddField(
            model_name="completeorder",
            name="pay_amount",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="pay_amount",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
