# Generated by Django 4.2 on 2023-04-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0013_alter_cartitem_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="complete_date",
            field=models.DateTimeField(null=True),
        ),
    ]
