# Generated by Django 4.2 on 2023-04-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0014_alter_order_complete_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="complete_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
