# Generated by Django 4.2 on 2023-04-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0015_alter_order_complete_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_received",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
