# Generated by Django 4.2 on 2023-04-08 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0017_order_delivered"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="completed",
        ),
    ]
