# Generated by Django 4.2 on 2023-04-08 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0019_paymentmethod_pay_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paymentmethod",
            old_name="pay_amount",
            new_name="multiplier",
        ),
    ]
