# Generated by Django 4.2 on 2023-04-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0020_rename_pay_amount_paymentmethod_multiplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivered",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_received",
            field=models.BooleanField(default=False),
        ),
    ]
