# Generated by Django 4.2 on 2023-04-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0022_rename_complete_date_order_delivery_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="type",
            field=models.CharField(
                choices=[("crypto", "crypto"), ("bank", "bank")],
                default="crypto",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
