# Generated by Django 4.2 on 2023-04-10 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0024_alter_paymentmethod_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="delivered",
            new_name="shipped",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="delivery_date",
            new_name="shipping_date",
        ),
    ]
