# Generated by Django 4.2 on 2023-04-10 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "market",
            "0026_shippingmethod_alter_order_user_alter_orderitem_item_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ShippingMethod",
            new_name="ShipmentMethod",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="shipping_method",
            new_name="shipment_method",
        ),
    ]
