# Generated by Django 4.2 on 2023-04-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0030_remove_orderitemvariation_orderitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="tracking_number",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
