# Generated by Django 4.2 on 2023-04-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0031_order_tracking_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="pm_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
