# Generated by Django 4.2 on 2023-04-19 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0032_order_pm_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="pm_name",
            new_name="pm_detail",
        ),
    ]
