# Generated by Django 4.2 on 2023-04-04 21:11

import accounts.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", accounts.manager.UserManager()),
            ],
        ),
    ]
