# Generated by Django 4.2 on 2023-04-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="insta",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
