# Generated by Django 4.2 on 2023-04-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_insta"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="allow_bank",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="allow_crypto",
            field=models.BooleanField(default=False),
        ),
    ]
