# Generated by Django 4.2 on 2023-04-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_allow_bank_user_allow_crypto"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="allow_cash",
            field=models.BooleanField(default=False),
        ),
    ]
