# Generated by Django 4.2 on 2023-04-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_allow_cash"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("street", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=50)),
                ("postcode", models.CharField(max_length=20)),
            ],
        ),
    ]
