# Generated by Django 4.2 on 2023-04-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_address_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="local",
            field=models.BooleanField(default=False),
        ),
    ]
